[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_sky_trade = "CYY6b6vWv84WQcE4trMRGXacGF3je92P6emYaYLtGcXP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
# cluster = "https://devnet.helius-rpc.com/?api-key=887524e6-92b0-4f96-973c-b37a53a9cfe4"
# cluster = "https://devnet.helius-rpc.com/?api-key=54107c74-c827-4550-840f-fb1215da8201"
# wallet = "/home/erenaspire7/.config/solana/id.json"
wallet = "/Users/ayomideaderojuola/.config/solana/id.json"
# wallet = "/Users/ayomideaderojuola/Documents/solana-rental/tests/wallets/centralizedAccount.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

