[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_sky_trade = "4KMuY3t3GfGHCzp94yC3QYV2bmzqKYNSdQjS8SxxJ7Zp"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "Localnet"
cluster = "https://devnet.helius-rpc.com/?api-key=887524e6-92b0-4f96-973c-b37a53a9cfe4"
wallet = "/home/erenaspire7/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
