[features]
seeds = false
skip-lint = false

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://boldest-wandering-moon.solana-devnet.quiknode.pro/e9af7ce40b11247cb6f6568aa2e886abf5dc4ef4/"
# cluster = "localnet"
# wallet = "/home/erenaspire7/.config/solana/id.json"
wallet = "/home/zeher/skyTradeLinks/solana-rental/wallets/devnet-keys/deploymentKey.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
